#!/system/bin/sh
# Aegis Fusion — pif-sync: mirror the active PIF fingerprint INTO the TEE
# profile (v3.1.0, Round 12 — direction INVERTED from v3.0.13–v3.0.17).
#
# Why the direction was inverted — the evidence chain (2026-09-10):
#   AlwaysStrong-TEESIM flashed on the same K70 test device reached three
#   greens with a config.json whose profile carries the PIF-spoofed Pixel
#   identity (generation mode, patchLevel.system = the pif's SECURITY_PATCH),
#   while this stack sat at one green with a real-identity profile. The
#   v3.0.13–v3.0.17 "keep the profile real" direction was derived from the
#   CannotAttestIds diagnostics of the OLD single-path sync; the AS runtime
#   config (57 packages + raw uid: pins for GMS/Vending/GSF) demonstrates the
#   passing shape: profile follows PIF, the PI core trio is uid-pinned, and
#   the PIF spoof flags are fully on. The v3.0.12-era -66 on GMS is explained
#   by the missing uid pins + switches-off residue of that era, not by the
#   synced identity itself (verification on device: Round 12 flash).
#
# This script's jobs (PIF active):
#   1. Mirror the PIF identity (brand/device/product/manufacturer/model) into
#      the profile — the attested device must match what DroidGuard sees.
#   2. Keep patchLevel.system on the PIF's SECURITY_PATCH and the patchLevel
#      value in OBJECT form ("patchLevel": {...}); a plain-string patchLevel
#      is silently dropped by TEES' ConfigStore (optJSONObject -> null).
#   3. Re-assert the STRONG spoof flags in our own bundled custom.pif.prop
#      (AS parity: autopif resets them to weak defaults; the Round 7 residue
#      left ALL switches at 0, which alone forces DEVICE to fail).
# Rollback paths:
#   - PIF removed        -> profile restored to the device's real identity.
#   - .pif-off           -> identity AND patch levels restored to real.
#   - .pif-sync-off      -> everything suppressed, profile untouched.
#
# Runs from service.sh: once at boot BEFORE the daemon reads config, and on
# the hourly tick. Any config change bounces the teesim daemon — service.sh
# respawns it within ~2s and the restart re-reads config.json and re-pushes.
# All paths are overridable for the test harness.

ADB="${AEGIS_ADB:-/data/adb}"
TEE_DIR="${AEGIS_TEE_DIR:-/data/adb/teesim}"
CFG="$TEE_DIR/config.json"
LOG="$TEE_DIR/pif-sync.log"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" >> "$LOG" 2>/dev/null; }
# Debug channel (v3.0.2): unified debug.log while /data/adb/teesim/.debug exists.
DBG_LOG="$TEE_DIR/debug.log"
dbg() { [ -f "$TEE_DIR/.debug" ] && echo "[$(date '+%F %T')] [pifsync] $*" >> "$DBG_LOG" 2>/dev/null; return 0; }
trim_log() { # keep the log bounded like keybox-fetch.log
    [ -f "$LOG" ] || return 0
    if [ "$(wc -l < "$LOG")" -gt 400 ]; then
        tail -n 200 "$LOG" > "$LOG.tmp" 2>/dev/null && mv "$LOG.tmp" "$LOG"
    fi
}

# Device properties, shim-able for tests.
if [ -n "$AEGIS_PROP_FILE" ]; then
    get_prop() {
        grep -o "\"$1\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" "$AEGIS_PROP_FILE" 2>/dev/null \
            | head -n 1 | sed 's/.*:[[:space:]]*"//;s/"$//'
    }
else
    get_prop() { getprop "$1" 2>/dev/null; }
fi

# Locate the active fingerprint config. The fusion's OWN bundled payload
# (aegisfusion module dir, custom.pif.prop generated by pif-fetch.sh or a
# user-provided prop/json) is checked first; /data/adb/pif.json is the legacy
# standard path; the rest are the layouts standalone PIF-class modules use
# (kept for users who prefer a standalone fingerprint module — the sync keeps
# both halves consistent either way).
PIF=""
for c in "$ADB/modules/aegisfusion_rs/custom.pif.prop" \
         "$ADB/modules/aegisfusion_rs/custom.pif.json" \
         "$ADB/pif.json" \
         "$ADB/modules/playintegrityfix/custom.pif.prop" \
         "$ADB/modules/playintegrityfix/custom.pif.json" \
         "$ADB/modules/playintegrityfix/pif.json" \
         "$ADB/modules/playintegrityfork/pif.json" \
         "$ADB/modules/Integrity-Box/pif.json" \
         "$ADB/modules/tricky_store/pif.json"; do
    if [ -s "$c" ]; then PIF="$c"; break; fi
done

[ -f "$CFG" ] || exit 0

# Restore the device's real identity into the profile. Rollback path only
# (PIF removed / .pif-off). Prop mapping matters: keystore2 (native daemon)
# fills the ATTESTATION_ID_* request params from these exact properties. The
# product id comes from ro.product.name — there is NO "ro.product.product"
# property on Android (v3.0.15 fix).
restore_real() {
    local_product=$(get_prop ro.product.name)
    [ -n "$local_product" ] || local_product=$(get_prop ro.build.product)
    set_id brand "$(get_prop ro.product.brand)"
    set_id device "$(get_prop ro.product.device)"
    set_id product "$local_product"
    set_id manufacturer "$(get_prop ro.product.manufacturer)"
    set_id model "$(get_prop ro.product.model)"
}

# set_id <json-field> <value> — replace an existing string value inside CFG.
# Empty value = leave the field alone. Idempotent: equal values don't count as
# a change (and don't trigger a daemon bounce). NOTE: for the patchLevel
# sub-keys (system/vendor/boot) this relies on those key names appearing only
# inside the patchLevel object — true for the TEES schema.
changed=0
set_id() {
    [ -n "$2" ] || return 0
    cur=$(sed -n "s/.*\"$1\":[[:space:]]*\"\([^\"]*\)\".*/\1/p" "$CFG" 2>/dev/null | head -n 1)
    [ "$cur" = "$2" ] && return 0
    # 剥换行 + 三层转义(M6,2026-09-16)。写入目标是 JSON 字符串,值里的 `"` 须
    # 落盘为 `\"`、`\` 须落盘为 `\\`;而 esc 还要再过一层 sed replacement
    # (replacement 会吃掉一层反斜杠:`\"` 被还原成裸引号),故每个反斜杠都要
    # 在 esc 里预翻倍——`\`→4 个、`"`→2 个+引号、`&`/`/` 加前置(分隔符)。
    # 顺序不可换:引号新增的反斜杠不能再被第一遍翻倍。
    esc=$(printf '%s' "$2" | tr -d '\n\r' \
        | sed -e 's/\\/\\\\\\\\/g' -e 's/"/\\\\"/g' -e 's/[&/]/\\&/g')
    sed -i "s/\"$1\":[[:space:]]*\"[^\"]*\"/\"$1\": \"$esc\"/" "$CFG" 2>/dev/null || return 0
    changed=1
    log "profiles.$1: '${cur:-<none>}' -> '$2'"
}

# ensure_patch_object <system-value> — TEES' ConfigStore reads patchLevel with
# optJSONObject(); a legacy plain-string value ("patchLevel": "2026-09-05")
# silently resolves to an EMPTY object there. Rewrite any string form into the
# canonical object shape, then keep patchLevel.system on <system-value>.
ensure_patch_object() {
    if tr -d "\n\r" < "$CFG" | grep -q '"patchLevel"[[:space:]]*:[[:space:]]*"'; then
        esc=$(printf '%s' "$1" | tr -d '\n\r' \
            | sed -e 's/\\/\\\\\\\\/g' -e 's/"/\\\\"/g' -e 's/[&/]/\\&/g')
        sed -i "s/\"patchLevel\"[[:space:]]*:[[:space:]]*\"[^\"]*\"/\"patchLevel\": { \"system\": \"$esc\", \"vendor\": \"YYYY-MM-05\", \"boot\": \"YYYY-MM-05\" }/" "$CFG" 2>/dev/null || return 0
        changed=1
        log "patchLevel: legacy string form rewritten to object (system=$1)"
    fi
}

# assert_flags — keep the STRONG spoof flags asserted in our own bundled
# custom.pif.prop (AS lite_pif_sync parity). autopif-class fetchers reset
# flags to weak defaults on every fetch, and the Round 7 diagnostic found all
# of them at 0 (the DroidGuard runtime check cannot pass in that state no
# matter what the TEE half does). Only OUR OWN payload file is touched — a
# standalone PIF module stays master of its own prop. Per-key overrides may
# be written to $TEE_DIR/spoof.conf (key=value lines), as in AS.
assert_flags() {
    case "$PIF" in
        "$ADB/modules/aegisfusion_rs/"*.prop) ;;
        *) return 0 ;;
    esac
    for kv in spoofBuild=1 spoofProps=1 spoofVendingFinger=1 spoofProvider=0; do
        k=${kv%%=*}; v=${kv#*=}
        o=$(sed -n "s/^$k=//p" "$TEE_DIR/spoof.conf" 2>/dev/null | head -1 | tr -d ' \r')
        [ -n "$o" ] && v=$o
        cur=$(sed -n "s/^$k=//p" "$PIF" 2>/dev/null | head -1 | tr -d '\r ')
        [ "$cur" = "$v" ] && continue
        if grep -q "^$k=" "$PIF" 2>/dev/null; then
            # v 也走同款转义:spoof.conf 虽是 root-only,但一个手滑写坏的值不应腐坏整个 prop 文件。
            # 注意这是 prop 文件而非 JSON(M6 勘误):prop 值里 `"` 合法,sed replacement 也原样输出,
            # 故这里不加 JSON 式引号转义(加了反而会往值里塞反斜杠)。
            esc_v=$(printf '%s' "$v" | tr -d '\n\r' | sed -e 's/[&/\\]/\\&/g')
            sed -i "s/^$k=.*/$k=$esc_v/" "$PIF" 2>/dev/null || continue
        else
            echo "$k=$v" >> "$PIF" 2>/dev/null || continue
        fi
        log "asserted $k=$v in $(basename "$PIF") (was '${cur:-<none>}')"
        changed=1
    done
}

# mirror_pif — copy the active PIF identity into the profile (Round 12 core).
# Fields fall back to FINGERPRINT components the way AS's teesim.sh does:
# google/caiman_beta/caiman:... -> brand=google, device=caiman, product=caiman_beta.
mirror_pif() {
    # pget reads BOTH payload formats: key=value prop lines (custom.pif.prop)
    # and the legacy JSON fingerprint files (pif.json / custom.pif.json).
    pget() {
        v=$(sed -n "s/^$1=//p" "$PIF" 2>/dev/null | head -1 | tr -d '\r"')
        if [ -z "$v" ]; then
            v=$(tr -d '\n\r' < "$PIF" 2>/dev/null \
                | grep -o "\"$1\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" \
                | head -1 | sed 's/.*:[[:space:]]*"//;s/"$//')
        fi
        printf '%s' "$v"
    }
    fp=$(pget FINGERPRINT)
    brand=$(pget BRAND)
    [ -z "$brand" ] && [ -n "$fp" ] && brand=$(printf '%s' "$fp" | cut -d/ -f1)
    device=$(pget DEVICE)
    [ -z "$device" ] && [ -n "$fp" ] && device=$(printf '%s' "$fp" | cut -d/ -f2)
    product=$(pget PRODUCT)
    [ -z "$product" ] && [ -n "$fp" ] && product=$(printf '%s' "$fp" | cut -d/ -f3)
    manu=$(pget MANUFACTURER)
    model=$(pget MODEL)
    set_id brand "$brand"
    set_id device "$device"
    set_id product "$product"
    set_id manufacturer "$manu"
    set_id model "$model"
    # patchLevel.system follows the pif; a non-date value degrades to "today"
    # (a value TEES resolves to the boot date), matching AS's bridge.
    sp=$(pget SECURITY_PATCH)
    case "$sp" in
        [0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]) ;;
        *) sp="today" ;;
    esac
    ensure_patch_object "$sp"
    set_id system "$sp"
}

# Legacy split-switch. It used to abort the whole script; that silently disarmed
# every later fix (post-mortem v3.1.1: a stale .pif-sync-off left over from an
# earlier experiment meant the Round 12 health checks NEVER ran). It now only
# suppresses the profile MIRRORING — the payload flag assertion below is a
# health check on our own shipped fingerprint config, not a profile change, and
# must run unconditionally or DroidGuard keeps seeing a disabled-build device.
SUPPRESS=""
if [ -f "$TEE_DIR/.pif-sync-off" ]; then
    SUPPRESS=1
    log ".pif-sync-off set: profile mirroring suppressed (payload flag health check still runs)"
fi

if [ -f "$TEE_DIR/.pif-off" ]; then
    # Kill-switch branch: revert EVERYTHING the sync ever wrote — identity AND
    # patch levels — so the TEE profile matches the device's real state.
    dbg "PIF half disabled via .pif-off — restoring the real device state"
    if [ -f "$TEE_DIR/.pif-synced" ]; then
        log ".pif-off set: restoring the real device identity and patch level"
        restore_real
        set_id system "$(get_prop ro.build.version.security_patch)"
        set_id vendor "$(get_prop ro.vendor.build.security_patch)"
        set_id boot "$(get_prop ro.vendor.build.security_patch)"
        rm -f "$TEE_DIR/.pif-synced"
    else
        dbg "profile already real — nothing to revert"
    fi
elif [ -z "$PIF" ]; then
    dbg "no fingerprint source found (synced marker: $([ -f "$TEE_DIR/.pif-synced" ] && echo yes || echo no))"
    if [ -f "$TEE_DIR/.pif-synced" ]; then
        log "fingerprint source no longer present; restoring the real device identity"
        restore_real
        rm -f "$TEE_DIR/.pif-synced"
    fi
else
    # PIF layer active: the profile follows the PIF (Round 12 direction) and
    # the STRONG spoof flags stay asserted in our own payload.
    if [ -z "$SUPPRESS" ]; then
        mirror_pif
        assert_flags
        log "PIF active ($PIF): identity + patchLevel.system mirrored, flags asserted"
        touch "$TEE_DIR/.pif-synced" 2>/dev/null
    else
        assert_flags
        log "PIF active ($PIF): mirroring suppressed, payload flags asserted"
    fi
fi

# Only a config CHANGE needs a re-push; identical values don't justify
# bouncing the daemon. Flag re-assertions also count (DroidGuard must restart
# to pick up a changed Build view). pidof misses in tests — no-op there.
if [ "$changed" = 1 ]; then
    dbg "profile/pif changed — bouncing teesim + DroidGuard"
    tpid=$(pidof teesim 2>/dev/null)
    if [ -n "$tpid" ]; then
        kill $tpid 2>/dev/null
        log "teesim daemon restarted to re-push the synced profile"
    else
        dbg "teesim not running (respawn loop will pick up the new config)"
    fi
    # The fingerprint the TEE profile now claims must match what DroidGuard
    # says on its next check — recycle its cached session so it re-reads the
    # (PIF-spoofed) props instead of answering from the old picture.
    dg=$(pidof com.google.android.gms.unstable 2>/dev/null)
    if [ -n "$dg" ]; then
        kill $dg 2>/dev/null
        log "DroidGuard (gms.unstable) recycled after the profile change"
    else
        dbg "gms.unstable not running — nothing to recycle"
    fi
    date +%s > "$TEE_DIR/.gms-recycle" 2>/dev/null
else
    dbg "profile unchanged — no bounce needed"
fi

trim_log
exit 0
